version: 1.0.0-rc-{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: >-
    dnvm update-self

    dnvm install 1.0.0-rc1-update1 -alias rc1u1

    dnvm use rc1u1
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dnu restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- cmd: dnx -p tests\Compose.Tests\ test
artifacts:
- path: artifacts/packages/**.nupkg
deploy:
- provider: NuGet
  name: development
  server: https://ci.appveyor.com/nuget/smudge202-46am3soaut15
  api_key:
    secure: fi5rlfPkAQ9yKX5ffuRSykvWTQbUqTp95PjfD00So1M=
  on:
    branch: dev
- provider: NuGet
  name: production
  api_key:
    secure: GauHc7DbZGcD8A4z+x6hToRqjurh0yQe/ky8TSjzBbRYug9ixYIsVnV/VDB8FT4H
  on:
    branch: master