version: 0.1.{build}
skip_tags: true
os: Visual Studio 2015 RC
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
- build.cmd
artifacts:
- path: artifacts/packages/**.nupkg
deploy:
- provider: NuGet
  name: development
  server: https://ci.appveyor.com/nuget/smudge202-46am3soaut15
  api_key:
    secure: fi5rlfPkAQ9yKX5ffuRSykvWTQbUqTp95PjfD00So1M=
  on:
    branch: dev
- provider: NuGet
  name: production
  api_key:
    secure: GauHc7DbZGcD8A4z+x6hToRqjurh0yQe/ky8TSjzBbRYug9ixYIsVnV/VDB8FT4H
  on:
    branch: master